name: CS-CoreLib
version: ${project.version}
authors: [TheBusyBiscuit, John000708, AlexLander123]
website: http://thebusybiscuit.github.io/

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

commands:
  cs_triggerinterface:
    description: Background Command
    usage: Dont use it
