name: CS-CoreLib
version: ${project.version}
authors: [mrCookieSlime, John000708, AlexLander123]
website: http://thebusybiscuit.github.io/

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

api-version: 1.14

commands:
  cs_triggerinterface:
    description: Background Command
    usage: Dont use it
